# Generated by Django 4.2.20 on 2025-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_modal',
            field=models.BooleanField(default=True),
        ),
    ]
