# Generated by Django 4.2.20 on 2025-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='short_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testreport',
            name='test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
