name: Deploy Django to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: hirecleo-app                 # Ditt appnamn i Azure
  AZURE_WEBAPP_PACKAGE_PATH: .                   # Roten av projektet
  PYTHON_VERSION: "3.12"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔧 Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: ⚙️ Run migrations
        run: |
          python manage.py migrate --noinput

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
