# Generated by Django 4.2.20 on 2025-05-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
