# Generated by Django 4.2.20 on 2025-06-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_delete_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
