# Generated by Django 4.2.20 on 2025-05-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_job_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
    ]
