# Generated by Django 4.2.20 on 2025-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='top_skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
