# Generated by Django 4.2.20 on 2025-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_candidate_top_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='candidate_pdfs/'),
        ),
    ]
