# Generated by Django 4.2.20 on 2025-04-12 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0005_candidate_uploaded_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
