# Generated by Django 4.2.20 on 2025-05-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testanalyzer', '0001_initial'),
        ('hello_world', '0005_chatsession_test_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobad',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testanalyzer.testresult'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobAd',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
