# Generated by Django 4.2.20 on 2025-05-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_world', '0010_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Ej angivet', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(default='Ej angivet', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Ej angivet', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='uploaded_pdf',
            field=models.FileField(blank=True, null=True, upload_to='job_pdfs/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
